### ISSUE TITLE
This package is misnamed

### ISSUE THREAD

**Issue by furrykef** [sindresorhus/strip-final-newline#1]
It doesn't strip out EOF (end of file) characters. It strips EOL (end of line) characters. An EOF character would mark the end of an entire file or stream, not just the end of a line. There isn't any EOF character in ASCII or Unicode, but EOT (0x04) and SUB (0x1a) come close.

This issue also exists in the readme for the execa package.

**Comment by sindresorhus** [comment]
You're right. It strips the last newline in the file. I must have been confused about the meaning of EOF when I made this module.

Any name suggestions?

- `strip-final-newline`
- `strip-last-newline`
- `strip-file-terminator`

I'm leaning towards number 1.

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by furrykef** [comment]
strip-file-terminator would have the same problem.

Aside from that, I have no personal preference for the name of the package; I don't use the package myself. I just happened across it while looking at the readme for the execa package.

strip-line-ending would be another possibility.
